### PR TITLE
Improvements to asset catalog compilation.

### PR DESCRIPTION
**Pull request by grp**
- Properly output list of output files.
 - Output complete dependency info, rather than leaving it empty.
 - Cleanup for compile output and unhanded options.
 - Add unit tests for compiling app icons and launch images.

This should be rebased, not squashed, since the commits are relatively unrelated.

### CODE REVIEW

**Comment by facebook-github-bot-5** [comment]
Thank you for your pull request.  As you may know, we require contributors to sign our Contributor License Agreement, and we don't seem to have you on file and listed as active anymore.  In order for us to review and merge your code, please email cla@fb.com with your details so we can update your status.

**Comment by facebook-github-bot-4** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by grp** [comment]
ping @marcsalem

**Comment by grp** [comment]
ping @marcsalem

**Comment by marcsalem** [comment]
Thanks! This looks good. I'll land it now.

**Pull request merged**
