### PR TITLE
Put linker option "-dependency_info $(dependency_info_file)" only on darwin

### PR DESCRIPTION
**Pull request by onhachoe**
linkers in other platforms won't have this option

### CODE REVIEW

**Comment by onhachoe** [comment]
Yeah, you have a point, but it is most likely that the target platform linker specification will inherit default domain linker which already have DependencyInfoFile set.
And sadly, AFAIK, there is no way to unset inherited property.
Suggestion on how to solve this?

**Comment by onhachoe** [comment]
Yeah, that sounds like a easy workaround for now.

**Comment by onhachoe** [comment]
Changed to check empty() for dependencyInfoFile

**Comment by grp** [comment]
Actually, I wonder if a linker that doesn't support this flag should be using the `com.apple.pbx.linkers.ld` specification at all, since that one is setup for the Darwin linker with many different flags, not just the dependency info ones. The `pbxbuild::Phase::FrameworksResolver` would need to not hardcode the linker identifier to use — I'm not sure where to get the identifier to use, though...

**Comment by grp** [comment]
This is good enough for now, though.

**Pull request merged**
