### PR TITLE
Fall back to submodule for libpng if not available.

### PR DESCRIPTION
**Pull request by grp**
Restructure external dependencies to search system then fall back to
local copies if not available. For libpng, add a local submodule.

### CODE REVIEW

**Comment by marcsalem** [comment]
Probably better to conditionally use this on a mac:

https://developer.apple.com/library/mac/documentation/GraphicsImaging/Reference/CGImage/index.html#//apple_ref/c/func/CGImageCreateWithPNGDataProvider

**Comment by grp** [comment]
This also replaces the custom installation script on Linux, which means one less installation procedure to maintain. I also think it's significantly simpler.

**Comment by facebook-github-bot-8** [comment]
Thank you for your pull request.  As you may know, we require contributors to sign our Contributor License Agreement, and we don't seem to have you on file and listed as active anymore.  In order for us to review and merge your code, please email cla@fb.com with your details so we can update your status.

**Comment by facebook-github-bot-6** [comment]
Thank you for your pull request.  As you may know, we require contributors to sign our Contributor License Agreement, and we don't seem to have you on file and listed as active anymore.  In order for us to review and merge your code, please email cla@fb.com with your details so we can update your status.

**Comment by grp** [comment]
Abandoning in favor of #87.

**Pull request closed without merging**
