### PR TITLE
Additionally search `PATH` for tools in xcrun.

### PR DESCRIPTION
**Pull request by grp**
In addition to the SDK, toolchains, and developer root. Also, refactor
executable search paths to require explicitly searching `PATH` rather
than treating it as a default.

### CODE REVIEW

**Comment by facebook-github-bot-3** [comment]
Thank you for your pull request.  As you may know, we require contributors to sign our Contributor License Agreement, and we don't seem to have you on file and listed as active anymore.  In order for us to review and merge your code, please email cla@fb.com with your details so we can update your status.

**Comment by facebook-github-bot-2** [comment]
Thank you for your pull request.  As you may know, we require contributors to sign our Contributor License Agreement, and we don't seem to have you on file and listed as active anymore.  In order for us to review and merge your code, please email cla@fb.com with your details so we can update your status.

**Comment by grp** [comment]
@strager, ping?

**Comment by strager** [comment]
lgtm

Do I merge by pressing the "Merge pull request" button?

**Comment by grp** [comment]
I either use that with the "squash and merge" option, or cherry-pick and push manually.

**Comment by grp** [comment]
Merged myself.

**Pull request closed without merging**
